### ISSUE TITLE
support dynamic/ generic number of input and output... 

### ISSUE THREAD

**Issue by eyadsibai** [samuell/sciluigi#2]
Some tasks the number of output depends on the input itself ... may be using a dictionary instead of a function per output...?

**Comment by samuell** [comment]
@eyadsibai Good point. This is aneed we're actually facing ourselves right now. Indeed, just supporting taking lists or dicts (just like in luigi), seems so far very easy to implement. I'm working on it right now.

**Comment by samuell** [comment]
@eyadsibai I actually thought of using something more static instead of functions.

The main problem here is that the paths for outputs can sometimes only be determined *after* the tasks are connected together into a network and the scheduling starts, especially if using the path of an upstream task target as basis for the output path (this is exactly what we do at UU, in order to keep track of which stages, and with which parameters, a file has been through to be created).

Thus, there seemingly needs to be a function there somewhere.

I'm thinking of a solution to this right now.

**Comment by eyadsibai** [comment]
```
class TaskMixin:
    input_source = luigi.Parameter()

    @staticmethod
    def get_input(input_source, key):
        if isinstance(input_source, dict):
            return input_source[key]
        elif isinstance(input_source, list):
            return list(map(TaskMixin.get_input, input_source))
        else:
            return input_source
```
function like that might work?
then u would call get_input in requires? may be?

**Comment by samuell** [comment]
@eyadsibai Something along these lines yet.

But doing dictionary lookup to get the right input is something I have tried hard to avoid, as that adds a dependency on the specific structure of the upstream targets correspondingoutput method. 

That is why in SciLuigi each input is now a separate field (with name `in_<inputname>`), so that you declare this connection info at the workflow level rather than inside the tasks.

This removes unnecessary dependencies between specific tasks, and thus makes the tasks more modular, so that they can more easily be swapped for another task on the workflow level.

----

But you are very right that multiple inputs and outputs are needed. To this end I have implemented support for lists of `TargetInfo` objects, (or functions returning such), in this commit: ea9183

Hope it fulfils what you are looking for?

**Comment by samuell** [comment]
So, what I mean is that in the cases where you would use a dict, you actually know what outputs you have, since you know the name of them, and then you would in SciLuigi be encouraged to created separate `in_<blabla>` fields for those ...

But is there a case where this is not appropriate and you are better of with a dict in anyway? Much interested to hear a little more about the use case behind this!

**Comment by samuell** [comment]
Ok, have now implemented rather generic functions, so that a task can take as input (and return as output) anything of:

# A TargetInfo object
# A function retuning a TargetInfo object
# A list containing items of any of type 1, 2, 3 in this list.

**Comment by samuell** [comment]
@eyadsibai Sorry for all the chatter, but I figured adding support for dicts as well, was so easy that there were no reason against allowing it ... so now you can have any combination of: dce9d54bc6f073da689705f516c133010c62e367

1. TargetInfos
2. Functions returning TargetInfos
3. Lists of 1, 2, 3, 4 in this list
4. Dicts of 1, 2, 3, 4 in this list.

Closing now. Please re-open if you think something is missing!

**Comment by chrstn-hntschl** [comment]
Sorry for opening this issue again but I have a related question:
I am using sciliugi for dealing with multi-class classification problems. I usually do not know in advance how many classes I have to deal with - I know this when I load my dataset in a DatasetProvider Task and extract to list of classes. I would like to run model training for each individual class as separate sciluigi task-pipeline (e.g. -> feature extraction, model selection, validation). Is it possible to have a task returning a dict (e.g. 'cat1': dataset1, 'cat2': dataset2} where the actual list of keys is only known when the DatasetProvider task is executed?

**Comment by ngr-t** [comment]
I bumped into an almost same problem.

In vanilla luigi, we can use "dynamic dependency" (call `yield` in `run()` method of `Task`) for that purpose, but it's not the case in `sciluigi`'s `WorkflowTask`.
As a dirty hack, we can override `sciluigi.WorkflowTask.run()` method and use dynamic deps after the point where we need it, but it seems that there we can't use SciLuigi style workflow construction using `sciluigi.Task`, `TargetInfo`, `in_xx` and `out_xx`.
